config/routes.rb
DbNinja::Application.routes.draw do
  devise_for :users
  get "users/home"
  get "users/list"
  
  root to: 'users#home'

  resources :constraints

  resources :projects do
    member do
      get :submit_query 
      post :report_query
      post :query_div
      post :constraints_load
      post :arguments_load
      post :load_function_field_div
      post :modify_graph
    end
    resources :collaborations
    resources :entities do
      resources :fields
    end
  end

end

app/models/entity.rb
class Entity < ActiveRecord::Base
  belongs_to :project
  has_many :fields , dependent: :destroy
  validates :table_name ,presence: true
  validates :model_name ,presence: true
  validates :project_id, uniqueness: { scope: :table_name,message: "Already Present" }
  validates :project_id, uniqueness: { scope: :model_name,message: "Already Present" }
  attr_accessible :project_id, :model_name, :table_name
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController

  before_action :get_instance_variables ,only: [:new,:index,:show,:update,:edit,:destroy,:create]
  before_action :get_entity , only: [:show,:update,:edit]
  before_action :check_collaborator,only: [:index,:show,:update,:edit]
  before_action :check_owner , only: [:new]
  before_action :check_url, only: [:show,:update,:edit]

  def index
    @entities = Project.find(params[:project_id]).entities
  end

  def new
    #@entity = Entity.new()
  end

  def create
    @entity = Entity.new(:project_id => params[:project_id].to_i , :model_name => params[:model_name] ,:table_name => params[:table_name])
    if @entity.save 
      flash[:success]="New Entity Added"
      redirect_to new_project_entity_path(@project)
    else
      @errors = @entity.errors.full_messages
      render 'new'
    end
    
  end

  def show
    @fields = @entity.fields
  end

  def update
  end

  def edit
  end

  def destroy
    Entity.find(params[:id]).destroy
    redirect_to project_entities_path(@project)
  end

  private

    def get_instance_variables
      @project = Project.find(params[:project_id])
      @owner = @project.user
    end

    def get_entity
      @entity = Entity.find(params[:id])
    end

end

app/views/entities/index.html.erb
<h1> Project Information </h1>
<div> 
	

	<ul class="nav nav-tabs">
    <li>
      <%= link_to("Project Information",  @project  , data: {toggle: ""} ) %>
    </li>

    <li >
      <%= link_to("Collaborators",  project_collaborations_path(@project)  , data: {toggle: ""} ) %>
    </li>

    <li class="active">
      <%= link_to("Table",  project_entities_path(@project)  , data: {toggle: ""} ) %>
    </li>
    <% if @project.collaborating_users.include? current_user %>
      <div class="navbar-search pull-right">
        <%= button_to "Collect Stats", submit_query_project_path(@project), :class => "btn btn-primary btn-medium", :method => :get %>
      </div>
    <%end%>
    <%#project=Project.find(params[:project_id].to_i)%>

    <%# if current_user == project.user %>
    	<!-- <div class="navbar-search pull-right"> -->
        <%#= form_tag(project_collaborations_path(Project.find(params[:project_id].to_i)), method: "post") do %>
          <!-- Email  -->
          <%#= text_field_tag(:email) %>
          <%#= hidden_field_tag :pid, project.id %>
          <%#= submit_tag("Add") %>
        <%# end %>
      <!-- </div> -->
    <%#end%>
  </ul>


  <div class="tab-content">

    <div id="table" class="tab-pane fade in active">
      <%= render partial: 'shared/index_entities' %>
    </div>
  </div>
	
</div>

app/views/entities/new.html.erb
<h1>Add a New Table</h1>

<div class="row">
  <div class="span2 ">
    <%= form_tag(project_entities_path(@project), method: "post") do%>
      <%=render partial:'shared/display_error_messages.html.erb' ,locals: {str: "Model name"} %>
      Model Name <%= text_field_tag(:model_name) %>

      <%=render partial:'shared/display_error_messages.html.erb' ,locals: {str: "Table name"} %>
      Table Name <%= text_field_tag(:table_name) %>

      <%= submit_tag("Add") %>
    <% end %>
  </div>
</div>

app/views/entities/show.html.erb
<% if current_user == @owner %>
  <%=link_to "Add Column", new_project_entity_field_path(@entity.project,@entity) ,method: "get"%>
<%end%>
<table class="table table-striped">
  <thead>  
    <tr>  
      <th>Name</th>  
      <th>Type</th>  
      <th>NULL</th>  
      <th>Default</th>  
      <% if current_user == @owner %>
        <th> Drop </th>
      <%end%>
    </tr>  
  </thead>  
  <tbody>  
    <% @fields.each do |field|%>
      <% name = Datatype.find(field.datatype_id).name %>
        <tr>  
          <td><%=field.name%></td>  

          <% if !(field.type_arg1.empty?) && !(field.type_arg2.empty?) %>
            <td><%= name.to_s + "(" + field.type_arg1.to_s + "," + field.type_arg2.to_s + ")" %></td>  
          <% elsif  !(field.type_arg1.empty?) %>
            <td><%= name.to_s + "(" + field.type_arg1.to_s + ")" %></td> 
          <%else%>
            <td><%=name.to_s%></td> 
          <%end%>

          <td><%=field.null_value%></td>
          <td><%=field.default%></td>  
          <% if current_user == @owner %>
            <td> <%=link_to "delete", project_entity_field_path(@project,@entity,field) ,method: "delete",data: { confirm: "Are you sure for deleting this field"}%></td>
          <%end%>
        </tr>
    <%end%>  
  </tbody>  
</table> 