config/routes.rb
DbNinja::Application.routes.draw do
  devise_for :users
  get "users/home"
  get "users/list"
  
  root to: 'users#home'

  resources :constraints

  resources :projects do
    member do
      get :submit_query 
      post :report_query
      post :query_div
      post :constraints_load
      post :arguments_load
      post :load_function_field_div
      post :modify_graph
    end
    resources :collaborations
    resources :entities do
      resources :fields
    end
  end

end

app/views/shared/_constraint.html.erb
<% return_type = function_id %>

<div class = "form-group check_blank">
  <%= select_tag  "constraint_#{((entity_counter.to_s + "_") + field_counter.to_s) +"_"+constraint_counter.to_s}",   options_for_select( Constraint.where("function_type = ? OR  function_type= ?", -1, return_type).collect{ |d| [  d.display_content , d.id ,{data: { id: d.id , return_type: FunctionReturnType.find(return_type).name }}] }.insert(0,"") ) , class: "field_above" %>
</div>


<% entity_counter%>
<% field_counter%>

app/views/shared/_display_entity.html.erb
<tr>

  <td>
    <%=entity.model_name%>
  </td>

  <td>
    <%=link_to  entity.table_name ,project_entity_path(@project,entity)%>
  </td>

  <% if current_user == @owner %>
    <td>
      <%= link_to "delete" , project_entity_path(@project,entity) ,method: :delete,data: { confirm: "Are you sure for deleting this entity"}   %>
    </td>
  <%end%>

</tr> 

app/views/shared/_display_error_messages.html.erb
<% unless @errors.nil? %>
  <% @errors.each do |error| %>
    <% if error.include? str %>
      <font color="red" size=1.5px>*<%=error%></font>
    <%end%>
  <%end%>
<%end%>

app/views/shared/_display_users.html.erb
<table class="table table-striped">

  <thead>  
    <tr>  
      <th>Name</th>  
      <th> Email</th>
    </tr>  
  </thead> 

  <tbody>  
    <% users.each  do |user| %>
      <tr>  
        <%= render partial: 'shared/print_user' , locals: {user: user}%>
      </tr>
    <%end%>
  </tbody> 

</table>
<%=will_paginate users%>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_home_table.html.erb
<td>
  <%= own.name %>
</td>

<td>
  <%= own.description %>
</td>

<td>
  <%= link_to "view" , own ,method: :get  %>
</td>

<% if yes=="1"%>
  <td> 
      <%= link_to "delete" , own ,method: :delete,data: { confirm: "Are you sure for deleting this project, it will delete all entities"}   %>        
  </td>
<%end%>

app/views/shared/_index_entities.html.erb
<%if  @entities.any? %>
  <table class="table table-striped">
    <thead>  
      <tr>  
        <th>Model Name</th>  
        <th>Table Name</th> 
        <% if current_user == @owner %>
          <th>Delete</th>
        <%end%>
      </tr>
    </thead>  
    <tbody>  
      <%@entities.each do |ent| %>
        <%= render partial: 'shared/display_entity' , locals: {entity: ent} %>
      <%end%>
    </tbody>  
  </table> 
<%else%>
  Currently no tables are there.
<%end%>

<div style = "padding: 20px 0 0 0">
  <% if current_user == @owner %>
    <%= button_to "Add Tables", new_project_entity_path, :class => "btn btn-primary btn-medium", :method => :get %>
  <%end%>
</div>  

app/views/shared/_load_form.html.erb
<% str = "argument"+"_"+entity_counter.to_s+"_"+field_counter.to_s+"_"+constraint_counter.to_s+"_"+argument_counter.to_s%>
<div class = "form-group span6 offset3 check_blank">
  <% if arg_name == "date" %>
    <%=text_field_tag str , nil , class: "Datepicker Constraint_Arg" , id: str %>
  <%elsif arg_name == "boolean"%>
    <%=check_box_tag str , true , false , class: "Constraint_Arg" , id: str %>
  <%else%>
    <%=text_field_tag str , nil , class: "Constraint_Arg" , id: str %>
  <%end%>
</div>
<% arg_name %>
<% "Arg_type "+arg_type.to_s + " sdjfkdsf" %>
<% constraint_counter %>
<% entity_counter %>
<% field_counter %>
<% argument_counter %>

app/views/shared/_load_function_field.js.erb
<%= select_tag  "function_field" ,  options_for_select( field.collect{ |d| [ d.name , d.name , {data: { arg: d.id}}] }.insert(0,"") ),:class => "function_field" %>

app/views/shared/_print_user.html.erb
<td>
  <%= user.name %>
</td>
<td>
  <%= user.email %>
</td>

app/views/shared/_project_show.html.erb
<h3> Description </h3>
<%= @project.description %>
<h3> Owner </h3>
<%= @project.user.name%> 
<h3> Host </h3>
<%= @project.host%>
<h3> Database Name </h3>
<%= @project.dbname %>

app/views/shared/_query_select_fields.html.erb
<%=content_tag :div ,class: "Properties" ,id: "property_#{counter}_1" do%> 
  <%= select_tag  "property_name_#{counter}_1" ,  options_for_select( field.collect{ |d| [ d.name , d.name , {data: { arg: d.id}}] }.insert(0,"") ),:class => "property_dropdown" %>
  
  <button class="add_property" type="button" disabled="disabled">Plus</button>

  <%=content_tag :div ,class: "Constraints span8 offset2" ,id: "constraints_#{counter}_1" do%> 
  <%end%>
<%end%>

app/views/shared/submit_query.html.erb
<%= form_tag( report_query_project_path(@project) , method: "post",data: {id: @project.id},id: "query_form") do %>
  
  <div class="form-group functions">
    <%= label_tag "Choose the Function"  %>
    <%= select_tag  "function" ,  options_for_select( [["Count","count"],["Maximum","max"],["Minimum","min"],["Average","avg"]]) %>

    <div class= "Function_entity">
      <%= label_tag "Choose the Entity on which function will work"  %>
      <%= select_tag  "function_entity" ,   options_for_select( @project.entities.collect{ |d| [ d.model_name , d.model_name , {data: { arg: d.id}}] }.insert(0,"") ) , class: "Function_Model" %>
    </div>
  </div>

  <h3 class="Entities" style = "display:none;"> Choose Grouping Parameters </h3>
  <div class="Entities" id="entity_1" style = "display:none;">
    <%= select_tag  "entity_name_1" ,   options_for_select( @project.entities.collect{ |d| [ d.model_name , d.model_name , {data: { arg: d.id}}] }.insert(0,"") ) , class: "model_select" %>
    <button class="add_entity" type="button" disabled="disabled" >Plus</button>
    <%=  tag("div", class:"span10 offset1 entity_above" , id: "entity_above_1" ) %>
      <%#=render partial:'shared/query_select_fields' ,locals: {field: @project.entities.first.fields,counter: "1"}%>
    </div>
  </div>

  <%= submit_tag("Submit" , class: "btn btn-primary btn-medium") %>

<div class="trash">
  <%#=text_field_tag(:msa, value = nil, id: "datepicker") %>
</div>

<% end %>

app/views/shared/trash_submit_query.html.erb
<%= form_tag( report_query_project_path(@project) , method: "post",data: {id: @project.id},id: "query_form") do %>
  
  <%= radio_button_tag 'gender', 'male' %> 
  <%= radio_button_tag 'gender', 'male' %> 
  <%= radio_button_tag 'gender', 'male' %> 
  <%= radio_button_tag 'gender', 'male' %> 
  <%= radio_button_tag 'gender', 'male' %> 
  <%= radio_button_tag 'gender', 'male' %> 
  

  <div class="form-group functions">
    <%= label_tag "Choose the Function"  %>
    <%= select_tag  "function" ,  options_for_select( [["Count","count"],["Maximum","max"],["Minimum","min"],["Average","avg"]]) %>

    <div class= "Function_entity">
      <%= label_tag "Choose the Entity on which function will work"  %>
      <%= select_tag  "function_entity" ,   options_for_select( @project.entities.collect{ |d| [ d.model_name , d.model_name , {data: { arg: d.id}}] }.insert(0,"") ) , class: "Function_Model" %>
    </div>
  </div>

  <h3 class="Entities" style = "display:none;"> Choose Grouping Parameters </h3>
  <div class="Entities" id="entity_1" style = "display:none;">

    <%= select_tag  "entity_name_1" ,   options_for_select( @project.entities.collect{ |d| [ d.model_name , d.model_name , {data: { arg: d.id}}] }.insert(0,"") ) , class: "model_select" %>
    <button class="add_entity" type="button" disabled="disabled" >Plus</button>
    <%=  tag("div", class:"span10 offset1 entity_above" , id: "entity_above_1" ) %>
      <%#=render partial:'shared/query_select_fields' ,locals: {field: @project.entities.first.fields,counter: "1"}%>
    </div>
  </div>

  <%= submit_tag("Submit" , class: "btn btn-primary btn-medium") %>

<div class="trash">
  <%#=text_field_tag(:msa, value = nil, id: "datepicker") %>
</div>

<% end %>