config/routes.rb
DbNinja::Application.routes.draw do
  devise_for :users
  get "users/home"
  get "users/list"
  
  root to: 'users#home'

  resources :constraints

  resources :projects do
    member do
      get :submit_query 
      post :report_query
      post :query_div
      post :constraints_load
      post :arguments_load
      post :load_function_field_div
      post :modify_graph
    end
    resources :collaborations
    resources :entities do
      resources :fields
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations , dependent: :destroy
  has_many :collaborating_users, through: :collaborations, source: :user
  has_many :project_models
  has_many :entities
  validates :name, presence: true
  validates :host, presence: true
  validates :adapter, presence: true
  validates :dbusername, presence: true
  validates :dbname , presence: true
  attr_accessible :name, :description, :dbusername, :adapter ,:host,:user_id ,:dbname
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :get_instance_variables ,only: [:show , :update , :edit ,:destroy,:submit_query, :query_div,:constraints_load,:load_function_field_div,:report_query]
  before_action :check_collaborator,only: [:show , :update , :edit,:submit_query]

  def new
    @project = Project.new()
  end

  def create
    @project = Project.new( :name => params["name"] , :description => params["description"] , :host => params["host"] ,:adapter => params["adapter"], :dbname => params["dbname"],:dbusername =>params["dbusername"])
    @project[:user_id] = current_user.id
    if @project.save
      Collaboration.create(:project_id => @project.id , :user_id => current_user.id)
      if params["LoadDataDb"] == "yes"
        add_project( params["dbusername"] , params["dbname"], params["password_of_db"])
      end
      flash[:success]  = "project Added"
      redirect_to root_url
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def show
    @project=Project.find(params[:id].to_i)
  end

  def update
  end
  
  def edit
  end

  def destroy
    @project.destroy
    redirect_to root_url
  end

  def submit_query

    @joining_params = []
    @all_entities = @project.entities
    @all_entities.each do
      |entity|
      fields = entity.fields
      fields.each do
        |field|
        a={}
        a["name"] = (entity.model_name.to_s + " <=> ")+field.name.to_s
        a["value"] = (entity.table_name.to_s + " <=> ")+field.name.to_s
        @joining_params.push(a)
      end
    end
  end

  def report_query
    @header = []
    @actual_header = []

    if ( params["coming_from_submit_query"] =="1")
      param = params.sort_by {|x,y| x}

      separate_where =[]

      param.each do
        |x,y|
        if x.include? "selection" and y =="where"
          separate_where.push(x.split("_")[1])
        end
      end

      entity_map = get_entity_map(param)
      field_map = get_field_map(param,entity_map)
      group_map = get_groups(field_map)
      constraints = get_constraints(group_map,param)
      @value = {}
      @where_clause = ""

      @extra_select_params = get_extra_select(param)

      @select_clause = @extra_select_params.join(',')

      @header = @extra_select_params

      if( @select_clause != "" )
        @select_clause = @select_clause + ","
      else
        @select_clause = ""
      end

      @select_clause = @select_clause +  params["function"] + "(" + params["function_entity"]+"."+params["function_field"]+")" 


      from_c,where_c = get_from_where ( param )

      arr = (from_c + entity_map.map { |x,y| y}).uniq

      @from_clause = arr.join(",")

      array_for_grouping = []
      group_map.each { 
        |x,y| 
        flag=false
        store_counter_id = ""
        y.each do
          |str|
          unless separate_where.include? str.split("_")[0]
            store_counter_id = str.split("_")[0]
            flag=true
          end
        end
        if flag 
          string_value = "grouping_function_"+store_counter_id
          function_name_is = params[string_value] + "("
          array_for_grouping.push(function_name_is + x[0]+"."+x[1] +')')
        end
      }
      @header =  array_for_grouping + @header 
      @actual_header = @header

      @group_clause = array_for_grouping.uniq.join(",")
      constraints.each do
        |x,y|
        z=""
        y.each do
          |s|
          vv = get_constraint_string(x[0]+"."+x[1],s.to_a,s.length-1)
          if ( vv != "")
            if( z== "")
              z = z+get_constraint_string(x[0]+"."+x[1],s.to_a,s.length-1)
            else
              z = z+" and "+get_constraint_string(x[0]+"."+x[1],s.to_a,s.length-1)
            end
          end
        end
        @value[x] = z
        if z!=""
          if @where_clause == ""
            @where_clause = @where_clause + z
          else
            @where_clause = @where_clause + " and " +z
          end
        end
      end

      if where_c.size>=1
        if @where_clause == ""
          @where_clause = where_c.join(' and ')
        else
          @where_clause = ( @where_clause + ' and ') + where_c.join(' and ')
        end
      end

      if @group_clause != ""
        @select_clause = @group_clause + "," + @select_clause
      end
      @query_to_be_fired = "select " + @select_clause + " from " + @from_clause 
      if @where_clause != ""
        @query_to_be_fired = @query_to_be_fired + " where " + @where_clause
      end
      if @group_clause != ""
        @query_to_be_fired = @query_to_be_fired + " group by " + @group_clause
      end
      @dbname = @project.dbname
      @dbusername = @project.dbusername
      @dbpassword = params[:dbpassword]
      @host = @project.host
      query = @query_to_be_fired

      if @host.include? ':'
        command = "mysql -h " + @host.split(':')[0] + " -p " + @host.split(':')[1] + "-D "+@dbname+" -u " + @dbusername + " -p"+@dbpassword+" -e " + "\""+query+"\""
      else
        #command = "mysql -h " + @host +  "-D "+@dbname+" -u " + @dbusername + " -p"+@dbpassword+" -e " + "\""+query+"\""
        command = "mysql -h " + " localhost " +  "-D "+@dbname+" -u " + @dbusername + " -p"+@dbpassword+" -e " + "\""+query+"\""
      end
      

      value = `#{command}`
      @ashish = command
      @making_graph = []
      if value != ""
        answer = value.split("\n")
        answer = answer[1,answer.size-1]
        answer.each_index do |i|
          answer[i] = answer[i].split("\t")
          push_value = answer[i][0,answer[i].size-1]
          v= []
          v.push(push_value)
          v.push ( answer[i][answer[i].size-1] )
          @making_graph.push(v)
        end
      end
      @actual_graph = @making_graph

    elsif (params["coming_from_submit_query"] =="2")
      @actual_graph = get_array_form(params["actual_graph"])
      @making_graph = @actual_graph
      @actual_header = get_header(params["actual_header"])
      @header = @actual_header

    elsif (params["coming_from_submit_query"] =="3")
      @actual_graph = get_array_form(params["actual_graph"])
      @actual_header = get_header(params["actual_header"])
      @making_graph = get_array_form(params["making_graph"])
      @header = get_header(params["header"])

      @minus_header = []
      @index_header = []
      
      params.each do |p,q|
        if p.include? "graph_group_"
          @minus_header.push(@header[q.to_i])
          @index_header.push(q.to_i)
        end
      end
      if (@index_header.size!=0 and params["fun_graph"] != "" )
        @header =  @minus_header
        @making_graph = find_new_graph(@index_header, @making_graph,params["fun_graph"])
      end
    else
      answer = get_array_form(params["making_graph"])
      @actual_graph = get_array_form(params["actual_graph"])
      @actual_header = get_header(params["actual_header"])
      @header = get_header(params["header"])
      if ( params.include? "operation")
        @making_graph = find_query(params["operation"],params["graph_argument_1"],params["graph_argument_2"],answer)
      end
    end
  end


  def query_div
    @entity = @project.entities.find(params["entity_selected"].to_i)
    @fields = @entity.fields
    @counter = params["entity_counter"]
    respond_to do |format|
      format.js {}
    end
  end

  def constraints_load   
    @field = Field.find(params["field_selected"].to_i)
    @entity_counter = params["entity_counter"]
    @field_counter  = params["field_counter"]

    respond_to do |format|
      format.js {}
    end
  end

  def load_function_field_div 
    @entity = @project.entities.find(params["entity_selected"].to_i)
    @fields = @entity.fields
    respond_to do |format|
      format.js {}
    end
  end

  def arguments_load
    @constraint = Constraint.find(params["constraint_selected"])
    @function = FunctionReturnType.find(@constraint.function_return_type_id);
    @argument = @constraint.arguments
    @entity_counter = params["entity_counter"]
    @field_counter = params["field_counter"]
    @constraint_counter = params["constraint_counter"]
    @return_type = params["return_value_above"]
    respond_to do |format|
      format.js{}
    end
  end

  private

    def find_query(operation,input1,input2,arr)
      answer = []
      arr.each do |x|
        if( operation == "1" )
          if( x[1].to_i > input1.to_i)
            answer.push(x)
          end
        end
        if( operation == "2" )
          if( x[1].to_i < input1.to_i)
            answer.push(x)
          end
        end
        if( operation == "3" )
          if( x[1].to_i > input1.to_i && x[1].to_i < input2.to_i)
            answer.push(x)
          end
        end
      end
      return answer
    end

    def get_array_form(input_string)
      answer  = []
      input_string = input_string.split('*&^%$#!@')

      input_string.each do
        |x|
        y = x.split('!@#~%$@#!')
        a=y[0,y.size-1]
        b= []
        b.push(a)
        b.push(y[y.size-1])
        answer.push(b)
      end
      return answer
    end

    def fun(arr,string)
      sum = 0 
      maximum =0
      minimum = arr[0]
      arr.each do |a|
        sum = sum + a.to_i
        maximum = ((maximum>a.to_i)? maximum : a.to_i)
        minimum = ((minimum>a.to_i)? a.to_i : minimum)
      end
      avg = sum / arr.size 
      if string == "Sum"
        return sum
      elsif string == "Average"
        return avg
      elsif string == "Maximum"
        return maximum
      elsif string == "Minimum"
        return minimum
      end
    end

    def find_new_graph(index_array,graph_to_be_modified,query_function)
      return_hash = {}
      graph_to_be_modified.each do |g|
        arr = []
        index_array.each do |i|
          arr.push(g[0][i])
        end
        if return_hash.has_key? arr
          return_hash[arr].push(g[1].to_i)
        else
          return_hash[arr]=[]
          return_hash[arr].push(g[1].to_i)
        end
      end

app/views/projects/arguments_load.js.erb
<% unless @function.name == "boolean" %>
  $('<%= "#constraint_"+@entity_counter.to_s+"_"+@field_counter.to_s+"_"+@constraint_counter.to_s%>').parent().after('<%= escape_javascript( render partial: "shared/constraint",locals: {function_id: @function.id,entity_counter: @entity_counter,field_counter: @field_counter,constraint_counter: @constraint_counter.to_i+1} )%>')
<%end%>

<%argument_counter = 0 %>

<% if @constraint.function_type == -1 %>
  <% argument_counter = argument_counter+ 1 %>
  $('<%= "#constraint_"+@entity_counter.to_s+"_"+@field_counter.to_s+"_"+@constraint_counter.to_s%>').after('<%= escape_javascript( render partial: "shared/load_form",locals: {arg_name: "",arg_type: @return_type,entity_counter: @entity_counter,field_counter: @field_counter,constraint_counter: @constraint_counter,argument_counter: argument_counter} )%>')
<%end%>


<% @argument.each do |arg| %>
  <% arg_type=FunctionReturnType.find(arg.type).name %>
  <% argument_counter = argument_counter+ 1 %>
  $('<%= "#constraint_"+@entity_counter.to_s+"_"+@field_counter.to_s+"_"+@constraint_counter.to_s%>').after('<%= escape_javascript( render partial: "shared/load_form",locals: {arg_name: arg.name,arg_type: arg_type,entity_counter: @entity_counter,field_counter: @field_counter,constraint_counter: @constraint_counter,argument_counter: argument_counter} )%>')
<%end%>

app/views/projects/collaborations.html.erb
<h1> Project Information </h1>
<div> 
  <ul class="nav nav-tabs">
    <li>
      <%= link_to("Project Information",  Project.find(params[:id].to_i)  , data: {toggle: ""} ) %>
    </li>

    <li class="active">
        <a data-toggle="tab" href="#coll">Collaborators</a>
    </li>

    <li>
        <a data-toggle="tab" href="#table">Tables</a>
    </li>

    <%project=Project.find(params[:id].to_i)%>
    <% if current_user == project.user %>
      <div class="navbar-search pull-right">
        <%= form_tag(collaborations_path, method: "post") do %>
          Email <%= text_field_tag(:email) %>
          <%= hidden_field_tag :pid, project.id %>
          <%= submit_tag("Add") %>
        <% end %>
      </div>
    <%end%>
  </ul>


  <div class="tab-content">
    <div id="info" class="tab-pane fade">       
    </div>
    <div id="coll" class="tab-pane fade in active">
      <h3>Collaborators</h3>
      <%= render partial: 'shared/display_users' , locals: {users: @collaborators}%>            
    </div>
    <div id="table" class="tab-pane fade">    
    </div>
  </div>
</div>

app/views/projects/constraints_load.js.erb
$('<%= "#constraints_"+@entity_counter.to_s+"_"+@field_counter.to_s%>').html('<%= escape_javascript( render partial: "shared/constraint",locals: {function_id: @field.datatype.function_return_type.id,entity_counter: @entity_counter,field_counter: @field_counter,constraint_counter: "1"} )%>');  

app/views/projects/load_function_field_div.js.erb
$(".functions").append('<%= escape_javascript( render partial: "shared/load_function_field",locals: {field: @fields} )%>')

app/views/projects/new.html.erb
<div class="row">
  <div class="span10 offset1">
    <h1>Add a New Project</h1>
  </div>
</div>  
<div class="row">
  <div class="span10 offset1">

    <%= form_tag( projects_path(@project) , method: "post" ) do %>

    <div class="form-group">

      <%#= f.label :project_name %>
      <%= label_tag "Project Name"  %>
      <%= text_field_tag :name%>

    </div>
    <div class="form-group">
      <%#= f.label :project_description %>
      <%= label_tag "Project Desciption"  %>
      <%= text_field_tag :description  %>
      <%#= f.text_field :description , class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag "Host"  %>
      <%= text_field_tag :host%>
      <%#= f.label :host_ip %>
      <%#= f.text_field :host, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag "Adapter Used for the project"  %>
      <%= text_field_tag :adapter %>

      <%#= f.label :adapter_used_for_your_application %>
      <%#= f.text_field :adapter, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag "Database Username"  %>
      <%= text_field_tag :dbusername%>

      <%#= f.label :database_username %>
      <%#= f.text_field :dbusername, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag "Database Name"  %>
      <%= text_field_tag :dbname%>

      <%#= f.label :database_name %>
      <%#= f.text_field :dbname, class: "form-control" %>
    </div>

    <div class = "form-group">
      <%= label_tag "Load Data from Databases Directly"%>
      <%= select_tag  "LoadDataDb" ,  options_for_select( [["No","no"],["Yes","yes"]]),class: "LoadDataDb " %>
    <div>

    <div class = "form-group PasswordDb" style = "display: none;">
      <%= label_tag "Enter your database password"%>
      <%= password_field_tag(:password_of_db,nil , class: "db_password_new") %>
      <%#= password_field_tag  "PasswordDb" ,class: "PasswordDb",style: "display:none;" %>
    </div>

    <%= submit_tag("Create my project" , class: "btn btn-large btn-primary create_new_project") %>
    <% end %>
  </div>
</div>

app/views/projects/query_div.js.erb
$('<%= "#entity_above_"+@counter.to_s%>').html('<%= escape_javascript( render partial: "shared/query_select_fields", locals: {field: @fields,counter: @counter,field_counter: @field_counter} )%>');  

app/views/projects/report_query.html.erb
<%#= @ashish %>
<% sending_data =[] %>
<% @making_graph.each do |x| %>
  <%sending_data.push ( x.join("!@#~%$@#!") ) %>
<%end%>
<% actual_data =[] %>
<% @actual_graph.each do |x| %>
  <%actual_data.push ( x.join("!@#~%$@#!") ) %>
<%end%>

<div class = "MMM" >
  <%= hidden_field_tag :making_graph , sending_data.join("*&^%$#!@"),id: "making_graph" %>
  <%= label_tag "Get Mean , Median or Mode"  %>
  <%= select_tag  "mean_median" ,  options_for_select( [["Get Mean","1"],["Get Median","2"],["Get Mode","3"]].insert(0,"")) , class: "mean_median" %>
  <input id="mmm" type = "text" >
</div>

<%= form_tag( report_query_project_path(@project) , method: "post",data: {id: @project.id}) do %>
  <%= hidden_field_tag :coming_from_submit_query, "2" %>
  <%= hidden_field_tag :project_id , @project.id ,id: "project_id"%>
  <%= hidden_field_tag :making_graph , sending_data.join("*&^%$#!@"),id: "making_graph" %>
  <%= hidden_field_tag :actual_graph , actual_data.join("*&^%$#!@"),id: "actual_graph" %> 
  <%= hidden_field_tag :header , @header.join("*&^%$#!@"),id: "header" %>
  <%= hidden_field_tag :actual_header , @actual_header.join("*&^%$#!@"),id: "actual_header" %> 
  <%= submit_tag("Load Original Graph" , class: "btn btn-primary btn-medium") %>
<%end%>

<%= form_tag( report_query_project_path(@project) , method: "post",data: {id: @project.id}) do %>
  <%= hidden_field_tag :coming_from_submit_query, "0" %>
  <%= hidden_field_tag :project_id , @project.id ,id: "project_id"%>
  <%= hidden_field_tag :making_graph , sending_data.join("*&^%$#!@"),id: "making_graph" %>
  <%= hidden_field_tag :actual_graph , actual_data.join("*&^%$#!@"),id: "actual_graph" %>  
  <%= hidden_field_tag :header , @header.join("*&^%$#!@"),id: "header" %>
  <%= hidden_field_tag :actual_header , @actual_header.join("*&^%$#!@"),id: "actual_header" %> 
  <div class = "graph_reduce">
    <%= label_tag "Choose the parameters for graph"  %>
    <%= select_tag  "operation" ,  options_for_select( [ ["","0"],["Entries greater than","1"],["Entries less than","2"],["Entires in between","3"]]) %>
    <input id = "graph1" type="text" name="graph_argument_1" disabled="disabled">
    <input id = "graph2" type="text" name="graph_argument_2" disabled="disabled">
  </div>
  <%= submit_tag("Submit" , class: "change_graph btn btn-primary btn-medium") %>
<%end%>

<% unless @header.size == 0 %>
  <h3> Further Grouping </h3>
  <%= form_tag( report_query_project_path(@project) , method: "post",data: {id: @project.id}) do %>
    <%= hidden_field_tag :coming_from_submit_query, "3" %>
    <%=hidden_field_tag :project_id , @project.id ,id: "project_id"%>
    <%= hidden_field_tag :making_graph , sending_data.join("*&^%$#!@"),id: "making_graph" %>
    <%= hidden_field_tag :actual_graph , actual_data.join("*&^%$#!@"),id: "actual_graph" %>  
    <%= hidden_field_tag :header , @header.join("*&^%$#!@"),id: "header" %>
    <%= hidden_field_tag :actual_header , @actual_header.join("*&^%$#!@"),id: "actual_header" %> 
    <div class = "function_choose">
      <%= label_tag "Choose the function for grouping"  %>
      <%= select_tag  "fun_graph" ,  options_for_select( [ ["","0"],["Sum","Sum"],["Average","Average"],["Maximum","Maximum"],["Minimum","Minimum"]]) %>
    </div>
    <div class = "graph_grouping">
      <% @header.each_index do |i| %>
        <div class = "form-group">
          <%= @header[i] %>
          <%= check_box_tag "graph_group_"+i.to_s, i %>
        </div>
      <%end%>
    </div>
    <%= submit_tag("Group" , class: "group_graph btn btn-primary btn-medium") %>
  <%end%>
<%end%>



<div class = "pie" >
  <%= pie_chart(@making_graph) %>
</div>

<div class ="column" >
  <%= column_chart @making_graph %>
</div>

app/views/projects/show.html.erb
<h1> Project </h1>
<div> 
  <ul class="nav nav-tabs">
    <li class="active">
      <a data-toggle="tab" href="#info">Project Information</a>
    </li>
    <li >
      <%= link_to("Collaborators",  project_collaborations_path(@project)  , data: {toggle: ""} ) %>
    </li>
    <li>
      <%= link_to("Tables",  project_entities_path(@project)  , data: {toggle: ""} ) %>
    </li>
    
    <% if @project.collaborating_users.include? current_user %>
      <div class="navbar-search pull-right">
        <%= button_to "Collect Stats", submit_query_project_path(@project), :class => "btn btn-primary btn-medium", :method => :get %>
      </div>
    <%end%>
    <%# if current_user == @project.user %>
      <!-- <div class="navbar-search pull-right"> -->
        <%#= form_tag(project_collaborations_path(@project), method: "post") do %>
          <!-- Email  -->
          <%#= text_field_tag(:email) %>
          <%#= hidden_field_tag :pid, @project.id %>
          <%#= submit_tag("Add") %>
        <%#end %>
      <!-- </div> -->
    <%#end%>
  </ul>


  <div class="tab-content">
    <div id="info" class="tab-pane fade in active">
      <%= render partial: "shared/project_show" %>
    </div>

    <div id="coll" class="tab-pane fade">
      <h3>Collaborators</h3>
      <div class = "row">
        <%@project.collaborating_users.each do%>
        <% |user| %>
        <div class="span8"><%= user.name %></div>
        <%end%>
      </div>
    </div>
    <div id="table" class="tab-pane fade">
      <h3>Section C</h3>
    </div>
  </div>
</div>

app/views/projects/submit_query.html.erb
<h1> Enter Your Query to collect your stats </h1>

<%= form_tag( report_query_project_path(@project) , method: "post",data: {id: @project.id},id: "query_form") do %>
  <%= hidden_field_tag :coming_from_submit_query, "1" %>  
  <div class = "form-group">
    <%= label_tag "Enter your database password"  %>
    <%= password_field_tag(:dbpassword,nil,class: "submit_query_password") %>
  </div>

  <div class="form-group functions">
    <%= label_tag "Choose the Function"  %>
    <%= select_tag  "function" ,  options_for_select( [["Count","count"],["Maximum","max"],["Minimum","min"],["Average","avg"]]) %>

    <div class= "Function_entity">
      <%= label_tag "Choose the Entity on which function will work"  %>
      <%= select_tag  "function_entity" ,   options_for_select( @project.entities.collect{ |d| [ d.model_name , d.table_name , {data: { arg: d.id}}] }.insert(0,"") ) , class: "Function_Model" %>
    </div>
  </div>
  <h3> Choose Joining Parameters </h3>
  <div class="Join_Div" id="join_div_1">
    <%= select_tag "join_tag_1" , options_for_select(@joining_params.collect {|d|   [ d["name"] , d["value"] ] }.insert(0,"") ) ,class: "Join",id: "join_1" %>
    is related to 
    <%= select_tag "relation_tag_1" , options_for_select(@joining_params.collect {|d|   [ d["name"] , d["value"] ] }.insert(0,"") ) ,class: "Join",id: "relate_1" %>
    <button class="join_add" type="button" disabled="disabled" >Plus</button>
  </div>

  <h3> Choose any other select parameters </h3>
  <div class = "select_div" id = "select_div_1" >
    <%= select_tag "select_tag_1" , options_for_select(@joining_params.collect {|d|   [ d["name"] , d["value"] ] }.insert(0,"") ) ,class: "Select",id: "select_1" %>
    <button class="select_add" type="button" disabled="disabled" >Plus</button>
  </div>
  <h3 class="Entities" style = "display:none;"> Choose Grouping Parameters </h3>
  <% @all_constraints = Constraint.where("function_type != ?", [-1]) %>
  <div class="Entities" id="entity_1" style = "display:none;">
    <div class="form-group">
      <%= select_tag( :sadsa, options_for_select( [["select me for giving conditon", "where"],["select me for grouping","group"]] ),id: "selection_1" , name: "selection_1",class: "Selection" ) %>
    </div>
    <div class="form-group">
      <%= select_tag( :sadsa, options_for_select(@all_constraints.collect{|d| [d["display_content"],d["sql_syntax"]] }.insert(0,"") ),id: "grouping_function_1" , name: "grouping_function_1",class: "GroupFunction",style: 'display: none;' ) %>
    </div>
    <%= select_tag  "entity_name_1" ,   options_for_select( @project.entities.collect{ |d| [ d.model_name , d.table_name , {data: { arg: d.id}}] }.insert(0,"") ) , class: "model_select" %>
    <button class="add_entity" type="button" disabled="disabled" >Plus</button>
    <%=  tag("div", class:"span10 offset1 entity_above" , id: "entity_above_1" ) %>
    </div>
  </div>
    

  <%= submit_tag("Submit" , class: "btn btn-primary btn-medium submit_submit_query") %>

<% end %>