config/routes.rb
DbNinja::Application.routes.draw do
  devise_for :users
  get "users/home"
  get "users/list"
  
  root to: 'users#home'

  resources :constraints

  resources :projects do
    member do
      get :submit_query 
      post :report_query
      post :query_div
      post :constraints_load
      post :arguments_load
      post :load_function_field_div
      post :modify_graph
    end
    resources :collaborations
    resources :entities do
      resources :fields
    end
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class = "nav navbar-nav pull-left">
          <li>
          <%= link_to "Data Analyser", root_path %>
        </li>
        </ul> 
        <ul class="nav navbar-nav pull-right">
          <li>
            <%= link_to "Home", root_path %>
          </li>
            <% if user_signed_in? %>          
              <li>
                <%= link_to "Add Project", new_project_path %> 
              </li>
              <li>
                <%= link_to "Users", users_list_path %> 
              </li>
              <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account<b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                      <li><%= link_to "Settings", edit_user_registration_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
                  </ul>
              </li>
            <%end%>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbNinja</title>
  <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container" style="margin-top: 50px">
	<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
  	<%= yield %>
	<%#= debug(params) if Rails.env.development? %>
</div>


</body>
</html>